name: Run Superintelligence Signal

on:
  schedule:
    - cron: "0 */6 * * *"  # Exécution toutes les 6 heures
  workflow_dispatch:       # Permet le déclenchement manuel si besoin

jobs:
  run-signal:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Run the signal program
      run: |
        python3 main.py
